version: '3'

services:
  detour:
    build: .
    ports:
     - "5000:5000"
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_NAME=detour
     - POSTGRES_PASS=postgres
     - POSTGRES_HOST=postgres
     - POSTGRES_PORT=5432
  postgres:
    image: postgres:9.6
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_DB=detour
