version: '3'

services:
  detour:
    build: .
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_NAME=detour
     - POSTGRES_PASS=postgres
     - POSTGRES_HOST=postgres
     - POSTGRES_PORT=5432
  postgres:
    image: postgres:9.6
    ports:
     - "5432:5444"
    environment:
     - POSTGRES_DB=detour
  nginx:
    image: nginx:latest
    ports:
      - "5000:80"
    volumes:
      - ./static:/static
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - detour
