version: '3.5'

services:
  detour:
    build: .
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_NAME=detour
      - POSTGRES_PASS=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - DJANGO_SETTINGS_MODULE=detour.settings.development
    volumes:
      - ./:/usr/src/app
    ports:
      - '5000:5000'
  postgres:
    image: postgres:9.6
    ports:
      - '5432:5444'
    environment:
      - POSTGRES_DB=detour
