# Generated by Django 2.1.4 on 2018-12-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('elevation', models.FloatField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('satellites', models.IntegerField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, max_length=100, null=True)),
                ('activity', models.CharField(blank=True, max_length=100, null=True)),
                ('battery', models.FloatField(blank=True, null=True)),
                ('annotation', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
