# Generated by Django 2.1.4 on 2018-12-09 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181208_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='speed',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip', to='api.Trip'),
        ),
    ]
