# Generated by Django 2.1.11 on 2019-12-21 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181209_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='point',
            name='speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='point',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='api.Trip'),
        ),
    ]
