# Generated by Django 2.1.11 on 2019-12-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_add_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='icon',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='trip',
            name='order',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
