# Generated by Django 2.1.11 on 2019-12-24 04:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_blog_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 24, 4, 18, 23, 584843)),
            preserve_default=False,
        ),
    ]
