# Generated by Django 2.1.15 on 2022-02-06 02:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_time_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='location',
            field=models.CharField(default='The world', help_text='Where the trip occurred geographically', max_length=1024),
        ),
        migrations.AddField(
            model_name='trip',
            name='slug',
            field=models.SlugField(default='name', help_text='Used for identification of the trip', max_length=100),
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_end',
            field=models.DateTimeField(default=datetime.datetime.utcnow, help_text='When the trip ended'),
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_start',
            field=models.DateTimeField(default=datetime.datetime.utcnow, help_text='When the trip started'),
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_time',
            field=models.CharField(blank=True, help_text="A textual description of when the trip occurred such as 'spring 2029'", max_length=256),
        ),
        migrations.AlterField(
            model_name='trip',
            name='description',
            field=models.TextField(help_text='A short blurb about the trip'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='name',
            field=models.CharField(help_text='A short title for the trip', max_length=100),
        ),
        migrations.AlterField(
            model_name='trip',
            name='visible',
            field=models.BooleanField(default=False, help_text='Whether to show the trip on the site or not'),
        ),
    ]
