# Generated by Django 2.1.15 on 2022-02-06 02:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0008_add_trip_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.TextField(help_text='The name of this memory')),
                ('description', models.TextField(blank=True, help_text='A short blurb about the trip')),
                ('image', models.ImageField(blank=True, help_text='An associated image', max_length=1024, upload_to='uploads/')),
                ('time', models.DateTimeField(help_text='When this memory occurred')),
                ('location', models.CharField(blank=True, help_text='Where this memory happened', max_length=1024)),
                ('lat', models.FloatField(blank=True, help_text='latitude if available', null=True)),
                ('lon', models.FloatField(blank=True, help_text='longitude if available', null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(help_text='The associated trip', on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='api.Trip')),
            ],
            options={
                'verbose_name_plural': 'memories',
            },
        ),
    ]
